config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get '/sign_in', as: 'signin', to: 'sessions#signin'
  get '/sign_out', as: 'signout', to: 'sessions#signout'
  get '/sign_up', as: 'signup', to: 'sessions#signup'

  get 'auth/sign_in', to: 'auth#signin'
  get 'auth/sign_out', to: 'auth#signout'

  get '/accounts', as: 'aws_accounts', to: 'accounts#index'
  get '/accounts/new', as: 'add_aws_account', to: 'accounts#new'
  post '/accounts', as: 'create_aws_account', to: 'accounts#create'
  get '/accounts/:id', as: 'show_aws_account', to: 'accounts#show'
  put '/accounts/:id', as: 'update_aws_account', to: 'accounts#update'
  delete '/accounts/:id', as: 'delete_aws_account', to: 'accounts#delete'
  get '/accounts/cf_update/:id', as: 'update_account_cf', to: 'accounts#update_cf'
  get '/account_creation_status', as: 'account_creation_status', to: 'accounts#account_creation_status'
  post '/gen_ext_id', as: 'generate_external_id', to: 'accounts#gen_new_external_id'
  get '/01c62a2dc9925b820a120f077fdbb7e6319184b0', as: 'error', to: 'home#error'

  # get "/landing", to: redirect(ENV['WEBSITE_URL']), status: 302
  # get "/docs", to: redirect(ENV['DOCS_URL']), status: 302

  patch '/settings/ignore_lists', as: 'update_ignore_lists', to: 'settings#update_ignore_lists'
  get '/preferences', as: 'preferences', to: 'settings#preferences'
  get '/notifications', as: 'notifications', to: 'settings#notifications'
  post '/preferences/generate_mfa_qr_code', as: 'generate_mfa_qr_code', to: 'settings#generate_mfa_qr_code'
  post '/preferences/configure_mfa', as: 'configure_mfa', to: 'settings#configure_mfa'
  delete '/preferences/mfa_device', as: 'delete_mfa_device', to: 'settings#delete_mfa_device'

  get '/views/network', as: 'network_view', to: 'network_view#index'
  get '/views/network/aws_nodes', as: 'network_view_nodes', to: 'network_view#aws_nodes'
  get '/views/network/aws_edges', as: 'network_view_edges', to: 'network_view#aws_edges'
  get '/views/network/vpc_info', as: 'network_vpc_info', to: 'network_view#vpc_info'
  get '/views/network/subnet_info', as: 'network_subnet_info', to: 'network_view#subnet_info'
  get '/views/network/tgw_info', as: 'networktgw_info', to: 'network_view#tgw_info'
  get '/views/network/igw_info', as: 'network_igw_info', to: 'network_view#igw_info'
  get '/views/network/account_info', as: 'network_account_info', to: 'network_view#account_info'
  get '/views/network/region_info', as: 'network_region_info', to: 'network_view#region_info'
  get '/views/network/ngw_info', as: 'network_ngw_info', to: 'network_view#ngw_info'
  get '/views/network/peering_info', as: 'network_peering_info', to: 'network_view#peering_info'
  get '/views/network/tgwattch_info', as: 'network_tgw_attch_info', to: 'network_view#tgwattch_info'
  post '/views/network/refresh_infra', as: 'refresh_network_infra', to: 'network_view#refresh_infra'
  post '/views/network/export_csv', as: 'export_network_csv', to: 'network_view#export_csv'
  get '/views/network/ec2instance_info', as: 'network_ec2_instance_info', to: 'network_view#ec2instance_info'
  get '/views/network/rdsAuroraInstance_info', as: 'network_rds_aurora_instance_info', to: 'network_view#rdsAuroraInstance_info'
  get '/views/network/rdsPostgresInstance_info', as: 'network_rds_postgres_instance_info', to: 'network_view#rdsPostgresInstance_info'
  get '/views/network/rdsMysqlInstance_info', as: 'network_rds_mysql_instance_info', to: 'network_view#rdsMysqlInstance_info'
  get '/views/network/awsLb_info', as: 'network_load_balancer_info', to: 'network_view#lb_info'
  get '/views/network/ecsCluster_info', as: 'network_ecs_cluster_info', to: 'network_view#ecsCluster_info'
  get '/views/network/ecsService_info', as: 'network_ecs_service_info', to: 'network_view#ecsService_info'
  get '/views/network/ec2Asg_info', as: 'network_ec2_asg_info', to: 'network_view#ec2_asg_info'
  get '/views/network/awsElb_info', as: 'network_elb_info', to: 'network_view#elb_info'
  get '/views/network/eksCluster_info', as: 'network_eks_cluster_info', to: 'network_view#eksCluster_info'
  get '/views/network/eksNodegroup_info', as: 'network_eks_nodegroup_info', to: 'network_view#eksNodegroup_info'
  get '/views/network/elasticacheRg_info', as: 'network_ec_repl_group_info', to: 'network_view#elasticacheRg_info'
  get '/views/network/elasticacheRedisCluster_info', as: 'network_ec_redis_cluster_info', to: 'network_view#elasticacheCluster_info'
  get '/views/network/elasticacheMemcachedCluster_info', as: 'network_ec_memcached_cluster_info', to: 'network_view#elasticacheCluster_info'

  get '/views/infrastructure', as: 'infrastructure_view', to: 'infrastructure_view#index'
  get '/views/infrastructure/aws_nodes', as: 'infrastructure_view_nodes', to: 'infrastructure_view#aws_nodes'
  get '/views/infrastructure/aws_edges', as: 'infrastructure_view_edges', to: 'infrastructure_view#aws_edges'
  get '/views/infrastructure/vpc_info', as: 'infrastructure_vpc_info', to: 'infrastructure_view#vpc_info'
  get '/views/infrastructure/subnet_info', as: 'infrastructure_subnet_info', to: 'infrastructure_view#subnet_info'
  get '/views/infrastructure/tgw_info', as: 'infrastructure_tgw_info', to: 'infrastructure_view#tgw_info'
  get '/views/infrastructure/igw_info', as: 'infrastructure_igw_info', to: 'infrastructure_view#igw_info'
  get '/views/infrastructure/account_info', as: 'infrastructure_account_info', to: 'infrastructure_view#account_info'
  get '/views/infrastructure/region_info', as: 'infrastructure_region_info', to: 'infrastructure_view#region_info'
  get '/views/infrastructure/ngw_info', as: 'infrastructure_ngw_info', to: 'infrastructure_view#ngw_info'
  get '/views/infrastructure/peering_info', as: 'infrastructure_peering_info', to: 'infrastructure_view#peering_info'
  get '/views/infrastructure/tgwattch_info', as: 'infrastructure_tgw_attch_info', to: 'infrastructure_view#tgwattch_info'
  get '/views/infrastructure/ec2instance_info', as: 'infrastructure_ec2_instance_info', to: 'infrastructure_view#ec2instance_info'
  get '/views/infrastructure/rdsAuroraInstance_info', as: 'infrastructure_rds_aurora_instance_info', to: 'infrastructure_view#rdsAuroraInstance_info'
  get '/views/infrastructure/rdsPostgresInstance_info', as: 'infrastructure_rds_postgres_instance_info', to: 'infrastructure_view#rdsPostgresInstance_info'
  get '/views/infrastructure/rdsMysqlInstance_info', as: 'infrastructure_rds_mysql_instance_info', to: 'infrastructure_view#rdsMysqlInstance_info'
  get '/views/infrastructure/awsLb_info', as: 'infrastructure_load_balancer_info', to: 'infrastructure_view#lb_info'
  get '/views/infrastructure/ecsCluster_info', as: 'infrastructure_ecs_cluster_info', to: 'infrastructure_view#ecsCluster_info'
  get '/views/infrastructure/ecsService_info', as: 'infrastructure_ecs_service_info', to: 'infrastructure_view#ecsService_info'
  get '/views/infrastructure/ec2Asg_info', as: 'infrastructure_ec2_asg_info', to: 'infrastructure_view#ec2_asg_info'
  get '/views/infrastructure/awsElb_info', as: 'infrastructure_elb_info', to: 'infrastructure_view#elb_info'
  get '/views/infrastructure/eksCluster_info', as: 'infrastructure_eks_cluster_info', to: 'infrastructure_view#eksCluster_info'
  get '/views/infrastructure/eksNodegroup_info', as: 'infrastructure_eks_nodegroup_info', to: 'infrastructure_view#eksNodegroup_info'
  get '/views/infrastructure/elasticacheRg_info', as: 'infrastructure_ec_repl_group_info', to: 'infrastructure_view#elasticacheRg_info'
  get '/views/infrastructure/elasticacheRedisCluster_info', as: 'infrastructure_ec_redis_cluster_info', to: 'infrastructure_view#elasticacheCluster_info'
  get '/views/infrastructure/elasticacheMemcachedCluster_info', as: 'infrastructure_ec_memcached_cluster_info', to: 'infrastructure_view#elasticacheCluster_info'
  post '/views/infrastructure/refresh_infra', as: 'refresh_infrastructure_view_infra', to: 'infrastructure_view#refresh_infra'
  post '/views/infrastructure/export_csv', as: 'export_infrastructure_csv', to: 'infrastructure_view#export_csv'
  scope :views do
    scope :infrastructure, controller: :infrastructure_view do
      get 'securityGroup_info', as: 'security_group_info', action: 'securityGroup_info'
      get 'aws_security_groups', as: 'aws_security_groups', action: 'aws_security_groups'
    end
  end

  get '/views/resiliency', as: 'resiliency_view', to: 'resiliency_view#index'
  get '/views/resiliency/aws_nodes', as: 'resiliency_view_nodes', to: 'resiliency_view#aws_nodes'
  get '/views/resiliency/ec2instance_info', as: 'resiliency_ec2_instance_info', to: 'resiliency_view#ec2instance_info'
  get '/views/resiliency/rdsAuroraInstance_info', as: 'resiliency_rds_aurora_instance_info', to: 'resiliency_view#rdsAuroraInstance_info'
  get '/views/resiliency/rdsPostgresInstance_info', as: 'resiliency_rds_postgres_instance_info', to: 'resiliency_view#rdsPostgresInstance_info'
  get '/views/resiliency/rdsMysqlInstance_info', as: 'resiliency_rds_mysql_instance_info', to: 'resiliency_view#rdsMysqlInstance_info'
  get '/views/resiliency/awsLb_info', as: 'resiliency_load_balancer_info', to: 'resiliency_view#lb_info'
  get '/views/resiliency/account_info', as: 'resiliency_account_info', to: 'resiliency_view#account_info'
  get '/views/resiliency/ecsCluster_info', as: 'resiliency_ecs_cluster_info', to: 'resiliency_view#ecsCluster_info'
  get '/views/resiliency/ecsService_info', as: 'resiliency_ecs_service_info', to: 'resiliency_view#ecsService_info'
  get '/views/resiliency/ec2Asg_info', as: 'resiliency_ec2_asg_info', to: 'resiliency_view#ec2_asg_info'
  get '/views/resiliency/awsElb_info', as: 'resiliency_elb_info', to: 'resiliency_view#elb_info'
  get '/views/resiliency/eksCluster_info', as: 'resiliency_eks_cluster_info', to: 'resiliency_view#eksCluster_info'
  get '/views/resiliency/eksNodegroup_info', as: 'resiliency_eks_nodegroup_info', to: 'resiliency_view#eksNodegroup_info'

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def update_ignore_lists
    updated = @current_user.update(
      ignored_aws_vpcs: (ignore_lists_params[:ignored_aws_vpcs]).split(",").map { |v| v.strip },
      # ignored_aws_subnets: (ignore_lists_params[:ignored_aws_subnets]).split(",").map { |s| s.strip },
      ignore_default_vpcs: ignore_lists_params[:ignore_default_vpcs]
    )
    unless updated
      @current_user.errors.messages.each do |field, errors|
        flash.now[field] = errors
      end
    end
    render :index
  end

  def delete_mfa_device
    cognito_client = Aws::CognitoIdentityProvider::Client.new(region: ENV['AWS_DEFAULT_REGION'])
    session_id = session[:cognito_session_id]
    cognito_session = @current_user.cognito_sessions.find(session_id)
    client = CognitoClient.new
    resp = client.refresh_id_token(cognito_session.refresh_token)
    access_token = resp.cognito_access_token

    cognito_client.set_user_mfa_preference({
      software_token_mfa_settings: {
        enabled: false,
        preferred_mfa: false
      },
      access_token: access_token
    })
    @current_user.mfa_device.destroy!
    redirect_to preferences_path
  end

  def generate_mfa_qr_code
    # TODO: So many things can go wrong here...
    # Refactor this.
    cognito_client = Aws::CognitoIdentityProvider::Client.new(region: ENV['AWS_DEFAULT_REGION'])
    session_id = session[:cognito_session_id]
    cognito_session = @current_user.cognito_sessions.find(session_id)
    client = CognitoClient.new
    resp = client.refresh_id_token(cognito_session.refresh_token)
    access_token = resp.cognito_access_token
    resp = cognito_client.associate_software_token({access_token: access_token})
    secret_code = resp.secret_code
    encoded_secret_code = "otpauth://totp/Quadzig:#{@current_user.email}?secret=#{secret_code}&issuer=Quadzig"
    qrcode = RQRCode::QRCode.new(encoded_secret_code)
    file_name = SecureRandom.uuid
    png = qrcode.as_png(
      bit_depth: 1,
      border_modules: 4,
      color_mode: ChunkyPNG::COLOR_GRAYSCALE,
      color: 'black',
      file: nil,
      fill: 'white',
      module_px_size: 6,
      resize_exactly_to: false,
      resize_gte_to: false,
      size: 240
    )

    IO.binwrite("/tmp/#{file_name}.png", png.to_s)
    
    json = {}
    json["filename"] = file_name
    json["content_type"] = 'image/png'
    json["data"] = Base64.encode64(File.read("/tmp/#{file_name}.png"))
    json["secret_code"] = secret_code
    render json: json
  end

  def configure_mfa
    cognito_client = Aws::CognitoIdentityProvider::Client.new(region: ENV['AWS_DEFAULT_REGION'])
    mfa_code = configure_mfa_params[:mfa_code]
    mfa_device_name = configure_mfa_params[:mfa_device_name]

    if !(/[0-9]{6,8}/ =~ mfa_code)
      flash[:mfa_errors] = ["Invalid MFA Code format! Please enter a valid MFA Code."]
      redirect_to preferences_path
      return
    end
    session_id = session[:cognito_session_id]
    cognito_session = @current_user.cognito_sessions.find(session_id)
    client = CognitoClient.new
    resp = client.refresh_id_token(cognito_session.refresh_token)
    access_token = resp.cognito_access_token

    begin
      cognito_client.verify_software_token({
        access_token: access_token,
        user_code: mfa_code, # required
        friendly_device_name: "MFA Device",
      })
    rescue Aws::CognitoIdentityProvider::Errors::EnableSoftwareTokenMFAException
      flash[:mfa_errors] = ["Invalid MFA Code format! The MFA Code you entered did not match with the scanned QR Code/Secret String. Please try again."]
      redirect_to preferences_path
      return
    end

    # If this fails for whatever reason, mfa process is still not complete yet
    mfa_device = @current_user.create_mfa_device(device_name: mfa_device_name)
    if !mfa_device.valid?
      if mfa_device.errors.details[:device_name].any? { |d| d[:error] == :invalid }
        flash[:mfa_errors] = ["Invalid MFA Device Name! Device Names can only contain alphabets, numbers, underscores, hyphens & spaces. Please try again."]
        redirect_to preferences_path
        return
      end
    end

    resp = cognito_client.set_user_mfa_preference({
      software_token_mfa_settings: {
        enabled: true,
        preferred_mfa: true
      },
      access_token: access_token
    })

    redirect_to preferences_path
  end

  def preferences
    @mfa_device = @current_user.mfa_device
    stripe_id = @current_user.subscription.stripe_id
    if stripe_id.nil?
      @user_not_setup_yet = true
      @tags = ["free"]
      @tags << "early-access" if $Emails.include? @current_user.email
      @aws_accounts_count = @current_user.aws_accounts.where(creation_complete: true).count
      @current_user.subscription.update!(
        tier: "free",
        aws_account_quantity: 3
      )
    else
      resp = Stripe::Subscription.list({
        customer: stripe_id
      })

      subscriptions = resp["data"]
      if subscriptions.count > 1
        raise StandardError.new("More than one subscription found for user #{stripe_id.inspect}")
      elsif subscriptions.count == 1
        @current_user.subscription.update!(
          tier: "enterprise",
          aws_account_quantity: subscriptions[0]["quantity"]
        )
      elsif subscriptions.count == 0
        @tags = ["free"]
        @tags << "early-access" if $Emails.include? @current_user.email
        @aws_accounts_count = @current_user.aws_accounts.where(creation_complete: true).count
        @current_user.subscription.update!(
          tier: "free",
          aws_account_quantity: 3
        )
      end
    end
    @subscription = @current_user.subscription
  end

  def notifications
  end

  private

  def ignore_lists_params
    params.require(:user).permit(:ignored_aws_vpcs, :ignore_default_vpcs)
  end

  def configure_mfa_params
    params.permit(:mfa_code, :mfa_device_name)
  end
end

app/views/settings/_enterprise.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <span><%= error %></span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        <h4>Your Subscription</h4>
      </div>
      <div class="card-body">
        <div class="list-group">
          <div class="list-group-item">
            <h5>Email ID</h5>
            <p><%= @current_user.email %></p>
          </div>
          <div class="list-group-item">
            <h5>Tier</h5>
            <h5><span class="badge badge-primary"><%= @subscription.tier.capitalize %></span></h5>
          </div>
          <div class="list-group-item">
            <h5>Subscription</h5>
            <p class="mb-0">You have subscribed to <span class="font-weight-bold mb-0"><%= @subscription.aws_account_quantity %> AWS Account(s)</span> at <span class="font-weight-bold">$<%= @subscription.aws_account_quantity.to_i * 10%>/Month</span></p>
            <small>This lets you visualize up to <span class="font-weight-bold"><%= @subscription.aws_account_quantity.to_i + 3 %> AWS Accounts</span>(3 AWS Accounts are free as part of Free Tier).</small>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <button class="btn btn-primary" id="manageBilling">Manage Subscription</button>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <%= render 'mfa' %>
  </div>
</div>

<div class="modal fade" id="cancelSubscription" tabindex="-1" role="dialog" aria-labelledby="cancelSubscriptionModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="cancelSubscriptionModal">We are sorry to see you go!</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you would like to cancel your subscription? Your subscription will be changed to Free Tier. You can continue using Quadzig with Free Tier even after cancelling your subscription.</p>
        <p>You will no longer be able to visualize more than 3 AWS Accounts. You will be refunded a pro-rated amount from your subscription in 7 to 10 business days.</p>
      </div>
      <div class="modal-footer">
        <%= link_to "Confirm Cancellation", cancel_subscription_path, method: :delete, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="updateSubscription" tabindex="-1" role="dialog" aria-labelledby="updateSubscriptionModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="updateSubscriptionModal">Change your Subscription?</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group row mb-1">
            <label for="awsAccountsCount" class="col-sm-8 col-form-label">Number of AWS Accounts</label>
            <div class="col-sm-4">
              <input type="number" class="form-control" id="awsAccountsCount" value="<%= @subscription.aws_account_quantity %>" min="1" oninput="validity.valid||(value='');">
            </div>
          </div>
          <div class="form-group row">
            <label for="currentSubscriptionAmount" class="col-sm-8 col-form-label">Current Subscription Price</label>
            <div class="col-sm-4">
              <input type="text" readonly class="form-control-plaintext" id="currentSubscriptionAmount" value="$ <%= @subscription.aws_account_quantity.to_i * 5 %>/Month">
            </div>
          </div>
          <div class="form-group row mb-1">
            <label for="subscriptionAmount" class="col-sm-8 col-form-label">New Subscription Price</label>
            <div class="col-sm-4">
              <input type="text" readonly class="font-weight-bold form-control-plaintext" id="subscriptionAmount" value="$ <%= @subscription.aws_account_quantity.to_i * 5 %>/Month">
            </div>
          </div>
        </form>
        <p>You can change your subscription any time you want. You will be billed on a pro rated basis.</p>
      </div>
      <div class="modal-footer">
        <a id="changeSubscription" class="btn btn-primary" href="#">Change Subscription</a>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'enterprise_prices' %>

app/views/settings/_mfa.html.erb
<div class="card">
  <div class="card-header">
    <h4>Settings</h4>
  </div>
  <div class="border-0 card-body">
    <% if @mfa_device %>
      <div class="list-group">
        <li class="list-group-item">
          <h5>MFA Device</h5>
          <p></i><%= @mfa_device.device_name %><i data-toggle="modal" data-target="#deleteMfaDeviceModal" id="deleteMfaDevice" class="text-danger ml-2 fas fa-trash"></i></p>
        </li>
      </div>
    <% else %>
      <div class="row">
        <div class="col-lg-12">
          <h6 class="mb-1">Multi Factor Authentication</h6>
          <p class="mb-1 d-block text-primary">Note: MFA is only available for users who signed up with Email & Password. Users signing up with Google cannot avail MFA functionality.</p>
          <button class="btn btn-primary" data-toggle="collapse" data-target="#mfaCollapsible" aria-expanded="false" aria-controls="mfaCollapsible">Activate MFA</button>
        </div>
      </div>
      <div class="collapse mt-3" id="mfaCollapsible">
        <div class="row">
          <div class="col-lg-12">
            <div class="mb-0 card card-body">
              <div class="row">
                <div class="col-lg-6">
                  <label class="font-weight-bold" for="mfaQrCodeContainer">QR Code</label>
                  <div id="mfaQrCodeContainer" style="height:200px; width: 200px;" class="d-flex justify-content-center m-0 p-0 card card-body">
                    <a id="activateMfa" class="text-center" href="#">Show QR Code</a>
                  </div>
                  <small class="text-primary">Note: If you are unable to load the QR Code image, you may have to log out and login to activate MFA.</small>
                </div>
                <div class="col-lg-6">
                  <%= form_with url: configure_mfa_path, method: :post, local: true  do |f| %>
                    <div class="form-group">
                      <label class="font-weight-bold">MFA Code</label>
                      <%= f.text_field :mfa_code, required: :required, style:"color: black", class: "form-control", placeholder:"634721", maxlength: 6 %>
                    </div>
                    <div class="form-group">
                      <label class="font-weight-bold">Device Name</label>
                      <%= f.text_field :mfa_device_name, required: :required, style:"color: black", class: "form-control", placeholder:"Work Iphone", maxlength: 128 %>
                    </div>
                    <%= f.submit "Configure MFA", class: "w-100 mt-2 btn btn-primary" %>
                    <p><small>Scan the QR Code in your Authenticator App & enter the resulting MFA code here. You can give your device a friendly name for reference.</small></p>
                  <% end %>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-12">
                  <p class="mt-2 mb-0">You can also enter the secret code directly. <a data-toggle="collapse" data-target="#secretCodeCollapsible" aria-expanded="false" aria-controls="secretCodeCollapsible" href="#" id="showSecretCode">Show Secret Code</a></p>
                  <div class="collapse" id="secretCodeCollapsible">
                    <pre class="mt-2 mb-0"><code><span id="mfaSecretCodeContainer"></span></code></pre>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% if @mfa_device %>
  <div class="modal fade" id="deleteMfaDeviceModal" tabindex="-1" role="dialog" aria-labelledby="deleteMfaDeviceModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="deleteMfaDeviceModalLabel">Delete MFA Device?</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Delete MFA Device <span class="font-weight-bold"><%= @mfa_device.device_name %></span>?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <%= form_with url: delete_mfa_device_path, method: :delete, local: true do |f| %>
            <%= f.submit "Delete MFA Device", class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= javascript_pack_tag 'mfa' %>

app/views/settings/index.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h4>Block Resources</h4>
          </div>
          <div class="card-body">
            <% if !flash[:errors].nil? && flash[:errors].class == Hash %>
              <div class="alert alert-danger" role="alert">
                <h4 class="alert-heading">There was an error updating your settings.</h4>
                <dl>
                  <% flash[:errors].each do |field, errors| %>
                    <dt><%= field.gsub("_", " ").camelize %></dt>
                    <dd><%= errors[0] %></dd>
                  <% end %>
                </dl>
              </div>
            <% end %>
            <%= form_with model: @current_user, url: update_ignore_lists_path, method: :patch, local: true do |f| %>
              <div class="form-group">
                <%= label_tag :ignored_aws_vpcs, "Ignored VPCs" %>
                <%= f.text_area :ignored_aws_vpcs, class: "form-control", placeholder: 'vpc-03ef3e55958c664f5,vpc-0f9b476fda5c861c4', value: @current_user.ignored_aws_vpcs.count > 0 ? @current_user.ignored_aws_vpcs.join(",") : "" %>
              </div>

              <div class="form-check">
                <%= f.check_box :ignore_default_vpcs, class: "form-check-input" %>
                <label class="form-check-label">
                  Ignore Default VPCs
                </label>
              </div>

              <%= f.submit "Save", class: 'mt-2 btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="alert alert-success" role="alert">
      <h4 class="alert-heading">Block Resources</h4>
      <p>You can instruct Quadzig to not discover & visualize specific resources by adding their AWS IDs here. Currently, we support blocking VPCs. In addition, you also have the option to hide specific resources in the Visualization dashboard.</p>
      <hr>
      <%= link_to 'https://docs.quadzig.io/#blocklists', class: 'btn btn-primary', target: '_blank' do %>Visit Docs <i class="fa fa-external-link-alt"></i><% end %>
    </div>
  </div>
</div>