config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get '/sign_in', as: 'signin', to: 'sessions#signin'
  get '/sign_out', as: 'signout', to: 'sessions#signout'
  get '/sign_up', as: 'signup', to: 'sessions#signup'

  get 'auth/sign_in', to: 'auth#signin'
  get 'auth/sign_out', to: 'auth#signout'

  get '/accounts', as: 'aws_accounts', to: 'accounts#index'
  get '/accounts/new', as: 'add_aws_account', to: 'accounts#new'
  post '/accounts', as: 'create_aws_account', to: 'accounts#create'
  get '/accounts/:id', as: 'show_aws_account', to: 'accounts#show'
  put '/accounts/:id', as: 'update_aws_account', to: 'accounts#update'
  delete '/accounts/:id', as: 'delete_aws_account', to: 'accounts#delete'
  get '/accounts/cf_update/:id', as: 'update_account_cf', to: 'accounts#update_cf'
  get '/account_creation_status', as: 'account_creation_status', to: 'accounts#account_creation_status'
  post '/gen_ext_id', as: 'generate_external_id', to: 'accounts#gen_new_external_id'
  get '/01c62a2dc9925b820a120f077fdbb7e6319184b0', as: 'error', to: 'home#error'

  # get "/landing", to: redirect(ENV['WEBSITE_URL']), status: 302
  # get "/docs", to: redirect(ENV['DOCS_URL']), status: 302

  patch '/settings/ignore_lists', as: 'update_ignore_lists', to: 'settings#update_ignore_lists'
  get '/preferences', as: 'preferences', to: 'settings#preferences'
  get '/notifications', as: 'notifications', to: 'settings#notifications'
  post '/preferences/generate_mfa_qr_code', as: 'generate_mfa_qr_code', to: 'settings#generate_mfa_qr_code'
  post '/preferences/configure_mfa', as: 'configure_mfa', to: 'settings#configure_mfa'
  delete '/preferences/mfa_device', as: 'delete_mfa_device', to: 'settings#delete_mfa_device'

  get '/views/network', as: 'network_view', to: 'network_view#index'
  get '/views/network/aws_nodes', as: 'network_view_nodes', to: 'network_view#aws_nodes'
  get '/views/network/aws_edges', as: 'network_view_edges', to: 'network_view#aws_edges'
  get '/views/network/vpc_info', as: 'network_vpc_info', to: 'network_view#vpc_info'
  get '/views/network/subnet_info', as: 'network_subnet_info', to: 'network_view#subnet_info'
  get '/views/network/tgw_info', as: 'networktgw_info', to: 'network_view#tgw_info'
  get '/views/network/igw_info', as: 'network_igw_info', to: 'network_view#igw_info'
  get '/views/network/account_info', as: 'network_account_info', to: 'network_view#account_info'
  get '/views/network/region_info', as: 'network_region_info', to: 'network_view#region_info'
  get '/views/network/ngw_info', as: 'network_ngw_info', to: 'network_view#ngw_info'
  get '/views/network/peering_info', as: 'network_peering_info', to: 'network_view#peering_info'
  get '/views/network/tgwattch_info', as: 'network_tgw_attch_info', to: 'network_view#tgwattch_info'
  post '/views/network/refresh_infra', as: 'refresh_network_infra', to: 'network_view#refresh_infra'
  post '/views/network/export_csv', as: 'export_network_csv', to: 'network_view#export_csv'
  get '/views/network/ec2instance_info', as: 'network_ec2_instance_info', to: 'network_view#ec2instance_info'
  get '/views/network/rdsAuroraInstance_info', as: 'network_rds_aurora_instance_info', to: 'network_view#rdsAuroraInstance_info'
  get '/views/network/rdsPostgresInstance_info', as: 'network_rds_postgres_instance_info', to: 'network_view#rdsPostgresInstance_info'
  get '/views/network/rdsMysqlInstance_info', as: 'network_rds_mysql_instance_info', to: 'network_view#rdsMysqlInstance_info'
  get '/views/network/awsLb_info', as: 'network_load_balancer_info', to: 'network_view#lb_info'
  get '/views/network/ecsCluster_info', as: 'network_ecs_cluster_info', to: 'network_view#ecsCluster_info'
  get '/views/network/ecsService_info', as: 'network_ecs_service_info', to: 'network_view#ecsService_info'
  get '/views/network/ec2Asg_info', as: 'network_ec2_asg_info', to: 'network_view#ec2_asg_info'
  get '/views/network/awsElb_info', as: 'network_elb_info', to: 'network_view#elb_info'
  get '/views/network/eksCluster_info', as: 'network_eks_cluster_info', to: 'network_view#eksCluster_info'
  get '/views/network/eksNodegroup_info', as: 'network_eks_nodegroup_info', to: 'network_view#eksNodegroup_info'
  get '/views/network/elasticacheRg_info', as: 'network_ec_repl_group_info', to: 'network_view#elasticacheRg_info'
  get '/views/network/elasticacheRedisCluster_info', as: 'network_ec_redis_cluster_info', to: 'network_view#elasticacheCluster_info'
  get '/views/network/elasticacheMemcachedCluster_info', as: 'network_ec_memcached_cluster_info', to: 'network_view#elasticacheCluster_info'

  get '/views/infrastructure', as: 'infrastructure_view', to: 'infrastructure_view#index'
  get '/views/infrastructure/aws_nodes', as: 'infrastructure_view_nodes', to: 'infrastructure_view#aws_nodes'
  get '/views/infrastructure/aws_edges', as: 'infrastructure_view_edges', to: 'infrastructure_view#aws_edges'
  get '/views/infrastructure/vpc_info', as: 'infrastructure_vpc_info', to: 'infrastructure_view#vpc_info'
  get '/views/infrastructure/subnet_info', as: 'infrastructure_subnet_info', to: 'infrastructure_view#subnet_info'
  get '/views/infrastructure/tgw_info', as: 'infrastructure_tgw_info', to: 'infrastructure_view#tgw_info'
  get '/views/infrastructure/igw_info', as: 'infrastructure_igw_info', to: 'infrastructure_view#igw_info'
  get '/views/infrastructure/account_info', as: 'infrastructure_account_info', to: 'infrastructure_view#account_info'
  get '/views/infrastructure/region_info', as: 'infrastructure_region_info', to: 'infrastructure_view#region_info'
  get '/views/infrastructure/ngw_info', as: 'infrastructure_ngw_info', to: 'infrastructure_view#ngw_info'
  get '/views/infrastructure/peering_info', as: 'infrastructure_peering_info', to: 'infrastructure_view#peering_info'
  get '/views/infrastructure/tgwattch_info', as: 'infrastructure_tgw_attch_info', to: 'infrastructure_view#tgwattch_info'
  get '/views/infrastructure/ec2instance_info', as: 'infrastructure_ec2_instance_info', to: 'infrastructure_view#ec2instance_info'
  get '/views/infrastructure/rdsAuroraInstance_info', as: 'infrastructure_rds_aurora_instance_info', to: 'infrastructure_view#rdsAuroraInstance_info'
  get '/views/infrastructure/rdsPostgresInstance_info', as: 'infrastructure_rds_postgres_instance_info', to: 'infrastructure_view#rdsPostgresInstance_info'
  get '/views/infrastructure/rdsMysqlInstance_info', as: 'infrastructure_rds_mysql_instance_info', to: 'infrastructure_view#rdsMysqlInstance_info'
  get '/views/infrastructure/awsLb_info', as: 'infrastructure_load_balancer_info', to: 'infrastructure_view#lb_info'
  get '/views/infrastructure/ecsCluster_info', as: 'infrastructure_ecs_cluster_info', to: 'infrastructure_view#ecsCluster_info'
  get '/views/infrastructure/ecsService_info', as: 'infrastructure_ecs_service_info', to: 'infrastructure_view#ecsService_info'
  get '/views/infrastructure/ec2Asg_info', as: 'infrastructure_ec2_asg_info', to: 'infrastructure_view#ec2_asg_info'
  get '/views/infrastructure/awsElb_info', as: 'infrastructure_elb_info', to: 'infrastructure_view#elb_info'
  get '/views/infrastructure/eksCluster_info', as: 'infrastructure_eks_cluster_info', to: 'infrastructure_view#eksCluster_info'
  get '/views/infrastructure/eksNodegroup_info', as: 'infrastructure_eks_nodegroup_info', to: 'infrastructure_view#eksNodegroup_info'
  get '/views/infrastructure/elasticacheRg_info', as: 'infrastructure_ec_repl_group_info', to: 'infrastructure_view#elasticacheRg_info'
  get '/views/infrastructure/elasticacheRedisCluster_info', as: 'infrastructure_ec_redis_cluster_info', to: 'infrastructure_view#elasticacheCluster_info'
  get '/views/infrastructure/elasticacheMemcachedCluster_info', as: 'infrastructure_ec_memcached_cluster_info', to: 'infrastructure_view#elasticacheCluster_info'
  post '/views/infrastructure/refresh_infra', as: 'refresh_infrastructure_view_infra', to: 'infrastructure_view#refresh_infra'
  post '/views/infrastructure/export_csv', as: 'export_infrastructure_csv', to: 'infrastructure_view#export_csv'
  scope :views do
    scope :infrastructure, controller: :infrastructure_view do
      get 'securityGroup_info', as: 'security_group_info', action: 'securityGroup_info'
      get 'aws_security_groups', as: 'aws_security_groups', action: 'aws_security_groups'
    end
  end

  get '/views/resiliency', as: 'resiliency_view', to: 'resiliency_view#index'
  get '/views/resiliency/aws_nodes', as: 'resiliency_view_nodes', to: 'resiliency_view#aws_nodes'
  get '/views/resiliency/ec2instance_info', as: 'resiliency_ec2_instance_info', to: 'resiliency_view#ec2instance_info'
  get '/views/resiliency/rdsAuroraInstance_info', as: 'resiliency_rds_aurora_instance_info', to: 'resiliency_view#rdsAuroraInstance_info'
  get '/views/resiliency/rdsPostgresInstance_info', as: 'resiliency_rds_postgres_instance_info', to: 'resiliency_view#rdsPostgresInstance_info'
  get '/views/resiliency/rdsMysqlInstance_info', as: 'resiliency_rds_mysql_instance_info', to: 'resiliency_view#rdsMysqlInstance_info'
  get '/views/resiliency/awsLb_info', as: 'resiliency_load_balancer_info', to: 'resiliency_view#lb_info'
  get '/views/resiliency/account_info', as: 'resiliency_account_info', to: 'resiliency_view#account_info'
  get '/views/resiliency/ecsCluster_info', as: 'resiliency_ecs_cluster_info', to: 'resiliency_view#ecsCluster_info'
  get '/views/resiliency/ecsService_info', as: 'resiliency_ecs_service_info', to: 'resiliency_view#ecsService_info'
  get '/views/resiliency/ec2Asg_info', as: 'resiliency_ec2_asg_info', to: 'resiliency_view#ec2_asg_info'
  get '/views/resiliency/awsElb_info', as: 'resiliency_elb_info', to: 'resiliency_view#elb_info'
  get '/views/resiliency/eksCluster_info', as: 'resiliency_eks_cluster_info', to: 'resiliency_view#eksCluster_info'
  get '/views/resiliency/eksNodegroup_info', as: 'resiliency_eks_nodegroup_info', to: 'resiliency_view#eksNodegroup_info'

app/views/layouts/_sidebar.html.erb
<div class="c-sidebar c-sidebar-dark c-sidebar-show">
	<ul class="c-sidebar-nav">
	  <li class="c-sidebar-nav-title">
      <img style="width: 100px" src="/sidebar_logo.png"/>
    </li>
    <li class="c-sidebar-nav-item c-sidebar-nav-dropdown">
      <a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
        <i class="mt-1 mr-2 far fa-map"></i> Views
      </a>
      <ul class="c-sidebar-nav-dropdown-items">
        <li class="c-sidebar-nav-item">
          <a class="c-sidebar-nav-link" href="<%= infrastructure_view_path(resource_group: @current_user.default_rg) %>" target="_top">
            <i class="mt-1 fas fa-cubes mr-2"></i> Infrastructure
          </a>
        </li>
        <li class="c-sidebar-nav-item">
          <a class="c-sidebar-nav-link" href="<%= network_view_path(resource_group: @current_user.default_rg) %>" target="_top">
            <i class="mt-1 fas fa-project-diagram mr-2"></i> Network
          </a>
        </li>
        <li class="c-sidebar-nav-item">
          <a class="c-sidebar-nav-link" href="<%= resiliency_view_path(resource_group: @current_user.default_rg) %>" target="_top">
            <i class="mt-1 fas fa-anchor mr-2"></i> Resiliency
          </a>
        </li>
      </ul>
    </li>
    <li class="c-sidebar-nav-item">
      <a class="c-sidebar-nav-link" href="<%= omnisearch_path %>">
        <i class="mt-1 fas fa-binoculars mr-2"></i> Omnisearch
      </a>
    </li>
    <li class="c-sidebar-nav-item">
      <a class="c-sidebar-nav-link" href="<%= aws_accounts_path %>">
        <i class="mt-1 fas fa-cloud mr-2"></i> Accounts
      </a>
    </li>

    <li class="c-sidebar-nav-item">
      <a class="c-sidebar-nav-link" href="<%= settings_path %>">
        <i class="mt-1 fas fa-ban mr-2"></i> Block Lists
      </a>
    </li>
    <li class="c-sidebar-nav-item">
      <a class="text-truncate c-sidebar-nav-link" href="/preferences">
        <i class="mt-1 mr-2 far fa-credit-card"></i> Subscriptions & Settings
      </a>
    </li>
    <li class="c-sidebar-nav-item">
      <a class="text-truncate c-sidebar-nav-link" href="/notifications">
        <i class="mt-1 mr-2 far fa-bell"></i> Notifications
        <% if @outdated_cf_template %>
          <span class="font-weight-bold p-2 badge bg-danger"><i class="fas fa-exclamation"></i></span>
        <% end %>
      </a>
    </li>
    <li class="flex-fill"></li>
    <li class="c-sidebar-nav-item">
      <a class="c-sidebar-nav-link c-sidebar-nav-link-danger" href="<%= signout_path %>">
        <i class="fas mt-1 mr-2 fa-sign-out-alt"></i> Sign Out
      </a>
    </li>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quadzig - Infrastructure visualization</title>
    <script defer src="https://js.stripe.com/v3/"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <% unless Rails.env == 'development' %>
      <%= javascript_pack_tag 'sentry' %>
    <% end %>
    <%= javascript_pack_tag 'application' %>
    <% if (["production", "staging"].include? Rails.env) && !@current_user.nil? %>
      <script>(function(f,b){if(!b.__SV){var e,g,i,h;window.mixpanel=b;b._i=[];b.init=function(e,f,c){function g(a,d){var b=d.split(".");2==b.length&&(a=a[b[0]],d=b[1]);a[d]=function(){a.push([d].concat(Array.prototype.slice.call(arguments,0)))}}var a=b;"undefined"!==typeof c?a=b[c]=[]:c="mixpanel";a.people=a.people||[];a.toString=function(a){var d="mixpanel";"mixpanel"!==c&&(d+="."+c);a||(d+=" (stub)");return d};a.people.toString=function(){return a.toString(1)+".people (stub)"};i="disable time_event track track_pageview track_links track_forms track_with_groups add_group set_group remove_group register register_once alias unregister identify name_tag set_config reset opt_in_tracking opt_out_tracking has_opted_in_tracking has_opted_out_tracking clear_opt_in_out_tracking start_batch_senders people.set people.set_once people.unset people.increment people.append people.union people.track_charge people.clear_charges people.delete_user people.remove".split(" ");
        for(h=0;h<i.length;h++)g(a,i[h]);var j="set set_once union unset remove delete".split(" ");a.get_group=function(){function b(c){d[c]=function(){call2_args=arguments;call2=[c].concat(Array.prototype.slice.call(call2_args,0));a.push([e,call2])}}for(var d={},e=["get_group"].concat(Array.prototype.slice.call(arguments,0)),c=0;c<j.length;c++)b(j[c]);return d};b._i.push([e,f,c])};b.__SV=1.2;e=f.createElement("script");e.type="text/javascript";e.async=!0;e.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?
        MIXPANEL_CUSTOM_LIB_URL:"file:"===f.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";g=f.getElementsByTagName("script")[0];g.parentNode.insertBefore(e,g)}})(document,window.mixpanel||[]);
        mixpanel.init("xxxxxxxx", {batch_requests: true})
        mixpanel.identify("<%= @current_user.id %>");
        mixpanel.people.set({
          "$email": "<%= @current_user.email %>",
          "account_count": <%= @current_user.aws_accounts.count %>
        })
      </script>
    <% end %>
  </head>

  <body class="c-app">
    <% if (@is_signed_in) %>
      <% if @show_sidebar %>
        <%= render 'layouts/sidebar' %>
      <% end %>
      <div id=<%="#{controller_name}-#{action_name}" %> class="c-wrapper">
        <div class="c-body">
          <main class="c-main">
            <div class="container">
              <div class="d-none" id="stripe_publishable_id"><%= ENV['STRIPE_PUBLISHABLE_KEY'] %></div>
              <div class="d-none" id="stripe_price_id"><%= ENV['ENTERPRISE_STRIPE_PRICE_ID'] %></div>
              <%= yield %>
              <%= render 'application/upgrade_tier' %>
            </div>
          </main>
        </div>
          <% if @show_footer %>
            <footer class="c-footer">
            </footer>
          <% end %> 
      </div>
    <!-- Landing Page rendering -->
    <% end %>
    <% if Rails.env == "production" %>
      <script>
          window.Userback = window.Userback || {};
          Userback.access_token = '29598|43087|aVuS3EaOSUrWNmSr4i9jFQjlF';
          Userback.categories = "Views, Omnisearch, Block Lists, General Feedback";
          (function(d) {
              var s = d.createElement('script');s.async = true;
              s.src = 'https://static.userback.io/widget/v1.js';
              (d.head || d.body).appendChild(s);
          })(document);
      </script>
    <% end %>
  </body>
</html>