config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get '/sign_in', as: 'signin', to: 'sessions#signin'
  get '/sign_out', as: 'signout', to: 'sessions#signout'
  get '/sign_up', as: 'signup', to: 'sessions#signup'

  get 'auth/sign_in', to: 'auth#signin'
  get 'auth/sign_out', to: 'auth#signout'

  get '/accounts', as: 'aws_accounts', to: 'accounts#index'
  get '/accounts/new', as: 'add_aws_account', to: 'accounts#new'
  post '/accounts', as: 'create_aws_account', to: 'accounts#create'
  get '/accounts/:id', as: 'show_aws_account', to: 'accounts#show'
  put '/accounts/:id', as: 'update_aws_account', to: 'accounts#update'
  delete '/accounts/:id', as: 'delete_aws_account', to: 'accounts#delete'
  get '/accounts/cf_update/:id', as: 'update_account_cf', to: 'accounts#update_cf'
  get '/account_creation_status', as: 'account_creation_status', to: 'accounts#account_creation_status'
  post '/gen_ext_id', as: 'generate_external_id', to: 'accounts#gen_new_external_id'
  get '/01c62a2dc9925b820a120f077fdbb7e6319184b0', as: 'error', to: 'home#error'

  # get "/landing", to: redirect(ENV['WEBSITE_URL']), status: 302
  # get "/docs", to: redirect(ENV['DOCS_URL']), status: 302

  patch '/settings/ignore_lists', as: 'update_ignore_lists', to: 'settings#update_ignore_lists'
  get '/preferences', as: 'preferences', to: 'settings#preferences'
  get '/notifications', as: 'notifications', to: 'settings#notifications'
  post '/preferences/generate_mfa_qr_code', as: 'generate_mfa_qr_code', to: 'settings#generate_mfa_qr_code'
  post '/preferences/configure_mfa', as: 'configure_mfa', to: 'settings#configure_mfa'
  delete '/preferences/mfa_device', as: 'delete_mfa_device', to: 'settings#delete_mfa_device'

  get '/views/network', as: 'network_view', to: 'network_view#index'
  get '/views/network/aws_nodes', as: 'network_view_nodes', to: 'network_view#aws_nodes'
  get '/views/network/aws_edges', as: 'network_view_edges', to: 'network_view#aws_edges'
  get '/views/network/vpc_info', as: 'network_vpc_info', to: 'network_view#vpc_info'
  get '/views/network/subnet_info', as: 'network_subnet_info', to: 'network_view#subnet_info'
  get '/views/network/tgw_info', as: 'networktgw_info', to: 'network_view#tgw_info'
  get '/views/network/igw_info', as: 'network_igw_info', to: 'network_view#igw_info'
  get '/views/network/account_info', as: 'network_account_info', to: 'network_view#account_info'
  get '/views/network/region_info', as: 'network_region_info', to: 'network_view#region_info'
  get '/views/network/ngw_info', as: 'network_ngw_info', to: 'network_view#ngw_info'
  get '/views/network/peering_info', as: 'network_peering_info', to: 'network_view#peering_info'
  get '/views/network/tgwattch_info', as: 'network_tgw_attch_info', to: 'network_view#tgwattch_info'
  post '/views/network/refresh_infra', as: 'refresh_network_infra', to: 'network_view#refresh_infra'
  post '/views/network/export_csv', as: 'export_network_csv', to: 'network_view#export_csv'
  get '/views/network/ec2instance_info', as: 'network_ec2_instance_info', to: 'network_view#ec2instance_info'
  get '/views/network/rdsAuroraInstance_info', as: 'network_rds_aurora_instance_info', to: 'network_view#rdsAuroraInstance_info'
  get '/views/network/rdsPostgresInstance_info', as: 'network_rds_postgres_instance_info', to: 'network_view#rdsPostgresInstance_info'
  get '/views/network/rdsMysqlInstance_info', as: 'network_rds_mysql_instance_info', to: 'network_view#rdsMysqlInstance_info'
  get '/views/network/awsLb_info', as: 'network_load_balancer_info', to: 'network_view#lb_info'
  get '/views/network/ecsCluster_info', as: 'network_ecs_cluster_info', to: 'network_view#ecsCluster_info'
  get '/views/network/ecsService_info', as: 'network_ecs_service_info', to: 'network_view#ecsService_info'
  get '/views/network/ec2Asg_info', as: 'network_ec2_asg_info', to: 'network_view#ec2_asg_info'
  get '/views/network/awsElb_info', as: 'network_elb_info', to: 'network_view#elb_info'
  get '/views/network/eksCluster_info', as: 'network_eks_cluster_info', to: 'network_view#eksCluster_info'
  get '/views/network/eksNodegroup_info', as: 'network_eks_nodegroup_info', to: 'network_view#eksNodegroup_info'
  get '/views/network/elasticacheRg_info', as: 'network_ec_repl_group_info', to: 'network_view#elasticacheRg_info'
  get '/views/network/elasticacheRedisCluster_info', as: 'network_ec_redis_cluster_info', to: 'network_view#elasticacheCluster_info'
  get '/views/network/elasticacheMemcachedCluster_info', as: 'network_ec_memcached_cluster_info', to: 'network_view#elasticacheCluster_info'

  get '/views/infrastructure', as: 'infrastructure_view', to: 'infrastructure_view#index'
  get '/views/infrastructure/aws_nodes', as: 'infrastructure_view_nodes', to: 'infrastructure_view#aws_nodes'
  get '/views/infrastructure/aws_edges', as: 'infrastructure_view_edges', to: 'infrastructure_view#aws_edges'
  get '/views/infrastructure/vpc_info', as: 'infrastructure_vpc_info', to: 'infrastructure_view#vpc_info'
  get '/views/infrastructure/subnet_info', as: 'infrastructure_subnet_info', to: 'infrastructure_view#subnet_info'
  get '/views/infrastructure/tgw_info', as: 'infrastructure_tgw_info', to: 'infrastructure_view#tgw_info'
  get '/views/infrastructure/igw_info', as: 'infrastructure_igw_info', to: 'infrastructure_view#igw_info'
  get '/views/infrastructure/account_info', as: 'infrastructure_account_info', to: 'infrastructure_view#account_info'
  get '/views/infrastructure/region_info', as: 'infrastructure_region_info', to: 'infrastructure_view#region_info'
  get '/views/infrastructure/ngw_info', as: 'infrastructure_ngw_info', to: 'infrastructure_view#ngw_info'
  get '/views/infrastructure/peering_info', as: 'infrastructure_peering_info', to: 'infrastructure_view#peering_info'
  get '/views/infrastructure/tgwattch_info', as: 'infrastructure_tgw_attch_info', to: 'infrastructure_view#tgwattch_info'
  get '/views/infrastructure/ec2instance_info', as: 'infrastructure_ec2_instance_info', to: 'infrastructure_view#ec2instance_info'
  get '/views/infrastructure/rdsAuroraInstance_info', as: 'infrastructure_rds_aurora_instance_info', to: 'infrastructure_view#rdsAuroraInstance_info'
  get '/views/infrastructure/rdsPostgresInstance_info', as: 'infrastructure_rds_postgres_instance_info', to: 'infrastructure_view#rdsPostgresInstance_info'
  get '/views/infrastructure/rdsMysqlInstance_info', as: 'infrastructure_rds_mysql_instance_info', to: 'infrastructure_view#rdsMysqlInstance_info'
  get '/views/infrastructure/awsLb_info', as: 'infrastructure_load_balancer_info', to: 'infrastructure_view#lb_info'
  get '/views/infrastructure/ecsCluster_info', as: 'infrastructure_ecs_cluster_info', to: 'infrastructure_view#ecsCluster_info'
  get '/views/infrastructure/ecsService_info', as: 'infrastructure_ecs_service_info', to: 'infrastructure_view#ecsService_info'
  get '/views/infrastructure/ec2Asg_info', as: 'infrastructure_ec2_asg_info', to: 'infrastructure_view#ec2_asg_info'
  get '/views/infrastructure/awsElb_info', as: 'infrastructure_elb_info', to: 'infrastructure_view#elb_info'
  get '/views/infrastructure/eksCluster_info', as: 'infrastructure_eks_cluster_info', to: 'infrastructure_view#eksCluster_info'
  get '/views/infrastructure/eksNodegroup_info', as: 'infrastructure_eks_nodegroup_info', to: 'infrastructure_view#eksNodegroup_info'
  get '/views/infrastructure/elasticacheRg_info', as: 'infrastructure_ec_repl_group_info', to: 'infrastructure_view#elasticacheRg_info'
  get '/views/infrastructure/elasticacheRedisCluster_info', as: 'infrastructure_ec_redis_cluster_info', to: 'infrastructure_view#elasticacheCluster_info'
  get '/views/infrastructure/elasticacheMemcachedCluster_info', as: 'infrastructure_ec_memcached_cluster_info', to: 'infrastructure_view#elasticacheCluster_info'
  post '/views/infrastructure/refresh_infra', as: 'refresh_infrastructure_view_infra', to: 'infrastructure_view#refresh_infra'
  post '/views/infrastructure/export_csv', as: 'export_infrastructure_csv', to: 'infrastructure_view#export_csv'
  scope :views do
    scope :infrastructure, controller: :infrastructure_view do
      get 'securityGroup_info', as: 'security_group_info', action: 'securityGroup_info'
      get 'aws_security_groups', as: 'aws_security_groups', action: 'aws_security_groups'
    end
  end

  get '/views/resiliency', as: 'resiliency_view', to: 'resiliency_view#index'
  get '/views/resiliency/aws_nodes', as: 'resiliency_view_nodes', to: 'resiliency_view#aws_nodes'
  get '/views/resiliency/ec2instance_info', as: 'resiliency_ec2_instance_info', to: 'resiliency_view#ec2instance_info'
  get '/views/resiliency/rdsAuroraInstance_info', as: 'resiliency_rds_aurora_instance_info', to: 'resiliency_view#rdsAuroraInstance_info'
  get '/views/resiliency/rdsPostgresInstance_info', as: 'resiliency_rds_postgres_instance_info', to: 'resiliency_view#rdsPostgresInstance_info'
  get '/views/resiliency/rdsMysqlInstance_info', as: 'resiliency_rds_mysql_instance_info', to: 'resiliency_view#rdsMysqlInstance_info'
  get '/views/resiliency/awsLb_info', as: 'resiliency_load_balancer_info', to: 'resiliency_view#lb_info'
  get '/views/resiliency/account_info', as: 'resiliency_account_info', to: 'resiliency_view#account_info'
  get '/views/resiliency/ecsCluster_info', as: 'resiliency_ecs_cluster_info', to: 'resiliency_view#ecsCluster_info'
  get '/views/resiliency/ecsService_info', as: 'resiliency_ecs_service_info', to: 'resiliency_view#ecsService_info'
  get '/views/resiliency/ec2Asg_info', as: 'resiliency_ec2_asg_info', to: 'resiliency_view#ec2_asg_info'
  get '/views/resiliency/awsElb_info', as: 'resiliency_elb_info', to: 'resiliency_view#elb_info'
  get '/views/resiliency/eksCluster_info', as: 'resiliency_eks_cluster_info', to: 'resiliency_view#eksCluster_info'
  get '/views/resiliency/eksNodegroup_info', as: 'resiliency_eks_nodegroup_info', to: 'resiliency_view#eksNodegroup_info'

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @id = session.id
    if params[:from_account_creation]
      @from_account_creation = true
    end

    @accounts = @current_user.aws_accounts
    @creation_completion_accounts = @current_user.aws_accounts.where(creation_complete: true)

    if @current_user.subscription.tier.to_s == "free" && @current_user.aws_accounts.where(creation_complete: true).count > 3
      if !@current_user.in_early_access_period?
        flash[:errors] = ["You have exceeded the free tier limit. Visualization views & Omnisearch will only work across 3 AWS Accounts as part of free tier."]
      end
    end

    @subscription = @current_user.subscription
    @allowed_ent_aws_account_quantity = @subscription.aws_account_quantity + 3
    if (@current_user.subscription.tier.to_s == "enterprise" && (@current_user.aws_accounts.where(creation_complete: true).count >= @allowed_ent_aws_account_quantity))
      @subscription_limit_reached = true
    end
  end

  def new
    # TODO: Fragile. Move to some kind of centralized checking
    @subscription = @current_user.subscription
    if @current_user.subscription.tier.to_s == "free" && @current_user.aws_accounts.where(creation_complete: true).count >= 3
      if !@current_user.in_early_access_period?
        flash.alert = "You have reached the limit of Free Tier. Please upgrade your subscription to visualize more AWS Accounts."
        redirect_to preferences_path
      end
    elsif (@current_user.subscription.tier.to_s == "enterprise" && (@current_user.aws_accounts.count >= (@subscription.aws_account_quantity + 3)))
      flash.alert = "You have reached the limit of your Enterprise Subscription. Please upgrade your subscription to visualize more AWS Accounts."
      redirect_to preferences_path
    end
    @cf_stack_name = "Quadzig-secure-access-#{SecureRandom.hex(8)}"
    @cf_link = CfTemplateVersion.where(is_latest: true).first.cf_link
    @external_id = SecureRandom.hex(20)
    @regions = AwsRegion.all
    user_id = @current_user.id
    @quadzig_account_id = ENV['QUADZIG_ACCOUNT_ID']
    APP_REDIS_POOL.with do |client|
      # 1 day
      client.set(@external_id, user_id, ex: 86400)
    end
  end

  def delete
    account = @current_user.aws_accounts.unscoped.find(account_del_params[:id])
    account.destroy!
    redirect_to aws_accounts_path
  end

  def show
    @account = @current_user.aws_accounts.find(params[:id])
  end

  def update
    # Careful here. Users might be able to edit params of other accounts
    # if we don't scope properly
    @account = @current_user.aws_accounts.find(params[:id])
    if @account.update(account_update_params)
      render :show
    else
      @account.errors.messages.each do |field, errors|
        flash.now[field] = errors
      end
      render :show
    end
  end

  def update_cf
    @account = @current_user.aws_accounts.find(params[:id])
    @latest_cf_version = CfTemplateVersion.where(is_latest: true).first
  end

  private

  def account_params
    # TODO: This should be aws_account. Not :account
    params.require(:account).permit(
      :external_id
    )
  end

  def account_del_params
    params.permit(:id)
  end

  def account_update_params
    params.require(:aws_account).permit(:id, :name, active_regions: [])
  end

  def acccount_creation_params
    params.permit(:externalId)
  end
end

app/views/accounts/index.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <span><%= error %></span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>
<% if flash[:info] %>
  <% flash[:info].each do |info| %>
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <span class="font-weight-bold"><%= info %></span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>
<% if @from_account_creation %>
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <span>Can't find an AWS Account? It usually takes a few minutes for Accounts to turn up here after account creation.</span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if @subscription_limit_reached %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <span>You have reached your Subscription Limit. Please upgrade your subscription to add more AWS Accounts. Visualization views will only show <%= @allowed_ent_aws_account_quantity %> AWS Accounts.</span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if @accounts.empty? %>
  <div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Welcome!</h4>
    <p>It looks like you have not configured any AWS Accounts yet. Please add an AWS Account to start visualizing your infrastructure.</p>
    <p class="font-weight-bold">If you have just added an AWS Account, your account should be available within a few minutes.</p>
    <hr>
    <%= link_to "Add AWS Account", add_aws_account_path, class: 'btn btn-primary' %>
  </div>
<% else %>
  <!-- Modal Start -->
  <% @accounts.each do |account| %>
    <div class="modal fade" id="deleteAccount<%= account.id %>" tabindex="-1" role="dialog" aria-labelledby="deleteAccountModel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="deleteAccountModel">Delete Account <%= account.name %>?</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete Account <span class="font-weight-bold"><%= account.name %></span>? You will no longer be able to visualize resources from this AWS Account. You can always add the AWS Account later again if you change your mind.</p>
            <p class="font-weight-bold">Deleting the AWS Account will not delete the Cloudformation Stack used to provision the Cross Account Role. Please delete the Cloudformation stack <span class="text-primary"><%= account.cf_stack_name %></span> to remove the provisioned cross account role.</p>
          </div>
          <div class="modal-footer">
            <%= link_to "Delete", delete_aws_account_path(account), method: :delete, class: 'btn btn-danger' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
    <!-- Modal End -->
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="d-flex card-header">
          <h4>Your AWS Accounts</h4>
          <span class="flex-fill"></span>
          <% if @subscription.tier.to_s == 'enterprise' %>
            <% if @creation_completion_accounts.count > @allowed_ent_aws_account_quantity %>
              <h6 class="text-danger align-self-center"><%= "Subscription Exceeded! #{@creation_completion_accounts.count} out of #{@allowed_ent_aws_account_quantity} AWS Accounts Used" %></h6>
            <% else %>
              <h6 class="align-self-center"><%= "Subscription: #{@creation_completion_accounts.count} out of #{@allowed_ent_aws_account_quantity} AWS Accounts Used" %></h6>
            <% end %>
          <% end %>
        </div>
        <div class="card-body">
          <table class="table table-striped table-hover table-bordered">
            <thead>
              <tr>
                <th scope="col">Name<i class="ml-1 fa fa-question-circle add-tooltip" data-toggle="tooltip" data-placement="top" title="We assign a friendly name to your AWS account during account creation. You can change the name from the 'View Account Screen'."></i></th>
                <th scope="col">Account ID</th>
                <th style="width: 40%" scope="col">State</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @accounts.each do |account| %>
                <tr>
                  <td>
                    <%= account.name %>
                  </td>
                  <!-- TODO: Processing string should be in yellow. Created in green -->
                  <td><%= account.account_id %></td>
                  <td>
                    <% if account.status.to_s == "created" %>
                      Created
                    <% elsif account.status.to_s == "processing" %>
                      <span>Processing</span> <i class="fa fa-question-circle add-tooltip" data-toggle="tooltip" data-placement="top" title="We are verifying that Quadzig has the correct IAM permissions to access your AWS account. If the status does not change to 'Created' within a few minutes of adding the AWS Account, please try deleting and re-adding the AWS Account. If this does not fix the issue, please get in touch with Quadzig Support."></i><a href="<%= request.path %>"><i class="ml-2 fas fa-redo-alt"></i></a>
                    <% elsif account.status.to_s == "deleted" %>
                      <span class="text-danger">Impaired! <i class="fas fa-exclamation-circle add-tooltip" data-toggle="tooltip" data-placement="top" title="The Cloudformation Stack associated with this AWS Account has been deleted! Please remove this AWS Account from Quadzig."></i></span>
                    <% elsif account.status.to_s == "error" %>
                      <p class="mb-0 text-danger">Error!</p>
                      <p class="mb-0 text-danger"><%= account.creation_errors[0] %></p>
                    <% end %>
                  </td>
                  <td class="d-flex">
                    <% if !account.cf_template_version.is_latest %>
                      <%= link_to update_account_cf_path(account), class: 'add-tooltip btn btn-warning', title:"Quadzig requires additional read permissions to support visualization of new AWS Resources.", data: { toggle: "tooltip", placement: "top" } do %>
                        Update Required
                        <i class="ml-2 fas fa-exclamation-triangle"></i>
                      <% end %>
                    <% end %>
                    <div class="flex-fill"></div>
                    <%= link_to "View/Edit", show_aws_account_path(account), class: 'ml-1 btn btn-primary' %>
                    <%= link_to "Delete", '#', { class: 'ml-3 btn btn-danger', 'data-toggle' => "modal", 'data-target' => "#deleteAccount#{account.id}" } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <% if @subscription_limit_reached %>
    <%= link_to "Add AWS Account", add_aws_account_path, class: 'disabled btn btn-primary' %>
  <% else %>
    <%= link_to "Add AWS Account", add_aws_account_path, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/accounts/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h4>Edit AWS Account</h4>
      </div>
      <div class="card-body">
        <%= form_with url: update_aws_account_path, method: :put, model: @account, local: true  do |f| %>
          <div class="form-group">
            <%= label_tag :name, "Account Name" %> <i class="fa fa-question-circle add-tooltip" data-toggle="tooltip" data-placement="top" title="A friendly name for your AWS Account."></i>
            <%= f.text_field :name, class: "dark-black form-control", "data-bind" => "text: accountName", placeholder: "Web Production Account" %>
          </div>
          <div class="form-group">
            <%= label_tag :iam_role_arn, "IAM Role ARN" %>
            <%= f.text_field :iam_role_arn, readonly: true, class: "dark-black form-control", placeholder: "arn:aws:iam::111111111111:role" %>
          </div>
          <div class="form-group">
            <%= label_tag :external_id, "External ID" %>
            <i class="fa fa-question-circle add-tooltip" data-toggle="tooltip" data-placement="top" title="External ID is used by Quadzig while discovering your AWS Resources. It provides an additional layer of security during cross Account IAM Role based access. Visit Quadzig docs to find out more."></i>
            <%= f.text_field :external_id, class: "form-control", readonly: true %>
          </div>
          <div class="form-group">
            <%= label_tag :cf_stack_name, "Cloudformation Stack Name" %>
            <i class="fa fa-question-circle add-tooltip" data-toggle="tooltip" data-placement="top" title="The name of the Cloudformation Stack that is used to provision the cross Account IAM Role. This role is used by Quadzig to discover your AWS Resources."></i>
            <%= f.text_field :cf_stack_name, class: "form-control", readonly: true %>
          </div>
          <div class="row">
            <div class="col-md-12">
              <%= label_tag :active_regions, "Active Regions" %>
              <i class="fa fa-question-circle add-tooltip" data-toggle="tooltip" data-placement="top" title="List of AWS Regions where you would like Quadzig to discover resources. You have to select at least one AWS Region to add an AWS Account. If you don't select any regions, Quadzig will by default discover resources in the N Virginia(us-east-1) region."></i>
              <div class="mb-2 form-check">
                <input class="form-check-input" type="checkbox" value="" id="selectAllRegions">
                <label class="form-check-label" for="selectAllRegions">
                  <span class="font-weight-bold">Select All</span>
                </label>
              </div>
              <div class="row">
                <%= f.collection_check_boxes(:active_regions, AwsRegion.all.sort_by { |r| r.region_code }, :region_code, :full_name, include_hidden: false) do |b| %>
                  <span class="col-4">
                    <%= b.check_box class: 'regionCheckbox' %>
                    <span class="mr-2 mb-2"><%= "#{b.object.full_name} (#{b.object.region_code})" %></span>
                  </span>
                <% end %>
              </div>
            </div>
          </div>
          <!-- TODO: Get this implementation checked -->
          <%= hidden_field(:aws_account, :ext_reference, value: @account.ext_reference) %>
          <%= f.submit "Save", class: 'mt-2 btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= javascript_pack_tag 'show_account' %>